FROM omninxt/oak4p-noetic-arm64:jp512

ARG USE_PROC=2
ENV DEBIAN_FRONTEND=noninteractive
ENV WORKSPACE=/catkin_ws

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      autoconf automake doxygen ipython3 \
      libblas-dev libboost-all-dev libeigen3-dev libglew-dev liblapack-dev \
      libopencv-dev libpoco-dev libsuitesparse-dev libtbb-dev libv4l-dev \
      python3-catkin-tools python3-dev python3-dill python3-igraph \
      python3-matplotlib python3-opencv python3-osrf-pycommon python3-pyx \
      python3-scipy python3-tk python3-wxgtk4.0 && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p "${WORKSPACE}/src"
COPY . /catkin_ws/src/tartancalib

RUN . /opt/ros/noetic/setup.sh && \
    cd "${WORKSPACE}" && \
    catkin init && \
    catkin config --extend /opt/ros/noetic --merge-devel \
      --cmake-args -DCMAKE_BUILD_TYPE=Release && \
    catkin build -j"${USE_PROC}" -p"${USE_PROC}" --no-status

RUN printf '%s\n' \
      'source /opt/ros/noetic/setup.bash' \
      'source /catkin_ws/devel/setup.bash' \
      'export KALIBR_MANUAL_FOCAL_LENGTH_INIT=1' \
      > /etc/profile.d/tartancalib.sh

CMD ["bash"]
