FROM nvcr.io/nvidia/l4t-jetpack:r35.4.1

ARG USE_PROC=2
ARG ROS_VERSION=noetic
ARG CUDA_ARCH_BIN=8.7
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
ENV ROS_DISTRO=${ROS_VERSION}
ENV PATH=/usr/local/cuda/bin:${PATH}
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib:${LD_LIBRARY_PATH}

RUN sed -i 's|http://ports.ubuntu.com/ubuntu-ports|https://mirrors.ustc.edu.cn/ubuntu-ports|g' \
      /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential ca-certificates cmake curl git gnupg2 lsb-release \
      pkg-config \
      libatlas-base-dev libboost-all-dev libceres-dev libeigen3-dev \
      libgoogle-glog-dev libgtk2.0-dev libjpeg-dev libpng-dev \
      libspdlog-dev libsuitesparse-dev libtbb-dev libtiff-dev \
      libyaml-cpp-dev libavcodec-dev libavformat-dev libavutil-dev \
      libswscale-dev libv4l-dev && \
    rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc \
      | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] https://mirrors.ustc.edu.cn/ros/ubuntu focal main" \
      > /etc/apt/sources.list.d/ros1.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      ros-${ROS_VERSION}-ros-base \
      ros-${ROS_VERSION}-image-transport \
      ros-${ROS_VERSION}-message-filters \
      ros-${ROS_VERSION}-pcl-ros \
      ros-${ROS_VERSION}-pcl-conversions \
      ros-${ROS_VERSION}-pluginlib \
      ros-${ROS_VERSION}-tf \
      ros-${ROS_VERSION}-tf2-ros \
      python3-catkin-tools python3-rosdep && \
    rm -rf /var/lib/apt/lists/*

COPY opencv /opt/src/opencv
COPY opencv_contrib /opt/src/opencv_contrib

RUN cmake -S /opt/src/opencv -B /opt/src/opencv/build \
      -D CMAKE_BUILD_TYPE=Release \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D OPENCV_DOWNLOAD_PATH=/opt/opencv-downloads \
      -D OPENCV_EXTRA_MODULES_PATH=/opt/src/opencv_contrib/modules \
      -D WITH_CUDA=ON \
      -D WITH_CUDNN=ON \
      -D WITH_CUBLAS=ON \
      -D CUDA_ARCH_BIN=${CUDA_ARCH_BIN} \
      -D CUDA_ARCH_PTX= \
      -D CUDA_FAST_MATH=ON \
      -D OPENCV_DNN_CUDA=ON \
      -D ENABLE_NEON=ON \
      -D WITH_EIGEN=ON \
      -D WITH_TBB=ON \
      -D WITH_IPP=OFF \
      -D WITH_OPENCL=OFF \
      -D BUILD_TESTS=OFF \
      -D BUILD_PERF_TESTS=OFF \
      -D BUILD_EXAMPLES=OFF \
      -D BUILD_opencv_apps=ON \
      -D BUILD_opencv_java=OFF \
      -D BUILD_opencv_python2=OFF \
      -D BUILD_opencv_python3=OFF \
      -D BUILD_LIST=calib3d,ccalib,core,cudaarithm,cudaimgproc,cudastereo,cudawarping,cudev,features2d,flann,highgui,imgcodecs,imgproc,photo,video,videoio && \
    cmake --build /opt/src/opencv/build --parallel ${USE_PROC} && \
    cmake --install /opt/src/opencv/build && \
    ldconfig && \
    opencv_version --verbose > /opt/opencv_build_information.txt && \
    rm -rf /opt/src/opencv /opt/src/opencv_contrib

RUN printf '%s\n' \
      'source /opt/ros/noetic/setup.bash' \
      'export PATH=/usr/local/cuda/bin:${PATH}' \
      'export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/lib:${LD_LIBRARY_PATH}' \
      > /etc/profile.d/omninxt-jp512.sh
